# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatKing', '0003_customuser_like_shop_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like_shop',
        ),
        migrations.DeleteModel(
            name='New_shop',
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='accuse_shop',
            name='accuser',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='accuse_shop',
            name='defendant',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='accuse_user',
            name='accuser',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='accuse_user',
            name='defendant',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='area_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='comment_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='env_score',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='rate',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='score_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='serv_score',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='taste_score',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='type_id',
            field=models.IntegerField(default=None),
        ),
    ]
