# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatKing', '0004_auto_20170701_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('shop_id', models.IntegerField(default=None)),
                ('taste_score', models.FloatField(default=None)),
                ('env_score', models.FloatField(default=None)),
                ('serv_score', models.FloatField(default=None)),
                ('like_num', models.IntegerField(default=None)),
                ('content', models.CharField(max_length=100)),
                ('create_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Like_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('shop_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='New_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcoation', models.CharField(max_length=254)),
                ('tel', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=None)),
                ('area_id', models.IntegerField(default=None)),
                ('type_id', models.IntegerField(default=None)),
                ('rate', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('shop_id', models.IntegerField(default=None)),
                ('create_at', models.DateField(default=None)),
            ],
        ),
    ]
