# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatKing', '0005_comment_like_shop_new_shop_recommend_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
