# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatKing', '0006_shop_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='env_score',
            new_name='env',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='serv_score',
            new_name='serv',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='taste_score',
            new_name='taste',
        ),
        migrations.AddField(
            model_name='shop',
            name='average',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='shop',
            name='dianping_addr',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='shop',
            name='open_time',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='shop',
            name='star',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
